"""initial schema

Revision ID: 65308f6143cf
Revises: 
Create Date: 2026-08-15 11:30:47.666850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65308f6143cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_banks_id'), 'blood_banks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('donor', 'requester', 'both', name='userrole'), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('donor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('next_eligible_date', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('id_document_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_donor_profiles_id'), 'donor_profiles', ['id'], unique=False)
    op.create_table('emergency_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('blood_type_needed', sa.String(length=5), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('urgency_level', sa.Enum('critical', 'urgent', 'planned', name='urgencylevel'), nullable=False),
    sa.Column('status', sa.Enum('open', 'matched', 'fulfilled', 'expired', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_requests_id'), 'emergency_requests', ['id'], unique=False)
    op.create_table('donation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=False),
    sa.Column('confirmed_by', sa.Enum('self_', 'hospital', name='confirmedby'), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_history_id'), 'donation_history', ['id'], unique=False)
    op.create_table('request_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('notified', 'accepted', 'declined', 'expired', name='matchstatus'), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['emergency_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_matches_id'), 'request_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_matches_id'), table_name='request_matches')
    op.drop_table('request_matches')
    op.drop_index(op.f('ix_donation_history_id'), table_name='donation_history')
    op.drop_table('donation_history')
    op.drop_index(op.f('ix_emergency_requests_id'), table_name='emergency_requests')
    op.drop_table('emergency_requests')
    op.drop_index(op.f('ix_donor_profiles_id'), table_name='donor_profiles')
    op.drop_table('donor_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_blood_banks_id'), table_name='blood_banks')
    op.drop_table('blood_banks')
    # ### end Alembic commands ###
